[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./tmp" }]

[fmt]
line_length = 80

[lint]
exclude_lints = [
    "mixed-case-function",
    "mixed-case-variable",
    "unwrapped-modifier-logic"
]
